services:
  fbi-bot-frontend:
    image: ghcr.io/mentalezuflucht/fbi-bot-frontend:latest
    container_name: fbi-bot-frontend
    restart: unless-stopped
    pull_policy: always

    environment:
      - API_URL=${API_URL}

    networks:
      br0:
        ipv4_address: ${FRONTEND_IP}

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  br0:
    external: true
